Repository Poten14/Componique, pull requests merged in 2024-08, with the labels that each got.

#8 feat: basic input 컴포넌트 구현(#1)
  src/app/(page)/sk/page.tsx
  src/components/Input/Input1.tsx
  tailwind.config.ts
  tsconfig.json
Labels: ✨ Feature, 🎨 Html&css

#5 feat: radio button1
  src/app/(page)/js/page.tsx
  src/components/RadioButton/RadioButton1.tsx
  src/components/RadioButton/RadioButton2.tsx
Labels: ✨ Feature, 🎨 Html&css

#34 Chore types
  src/app/(page)/sk/page.tsx
  src/components/Input/Input1.tsx
  src/components/Input/SearchInput.tsx
  src/components/Input/SearchInput2.tsx
  src/components/Input/SearchInput3.tsx
  src/components/Spinner/BasicSpinner.tsx
  src/types/type.ts
Labels: 📃 Docs

#10 feat: basic navbar 컴포넌트 구현(#2)
  public/images/logo.svg
  public/images/searchIcon.svg
  src/app/(page)/yr/page.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/NavbarSearch.tsx
Labels: ✨ Feature, 🎨 Html&css

#12 feat: 버튼 컴포넌트 구현
  src/app/(page)/dw/page.tsx
  src/components/Button/Button.tsx
Labels: ✨ Feature, 🎨 Html&css

#14 feat: Card1 clear
  src/app/(page)/js/page.tsx
  src/components/Card/Card1.tsx
Labels: ✨ Feature, 🎨 Html&css

#20 feat: Card3 clear
  public/componique_logo.svg
  src/app/(page)/js/page.tsx
  src/components/Card/Card3.tsx
Labels: ✨ Feature, 🎨 Html&css

#22 feat: basic textarea 컴포넌트 구현
  src/app/(page)/sk/page.tsx
  src/app/(page)/yr/page.tsx
  src/components/Input/Input1.tsx
  src/components/Textarea/Textarea.tsx
Labels: ✨ Feature, 🎨 Html&css

#23 feat: Card4 clear
  src/app/(page)/js/page.tsx
  src/app/globals.css
  src/components/Card/Card4.tsx
Labels: ✨ Feature, 🎨 Html&css

#29 feat: 기본 체크박스 컴포넌트 구현
  package.json
  src/app/(page)/dw/page.tsx
  src/app/(page)/sk/page.tsx
  src/components/CheckBox/CheckBox.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#32 feat: Card5 clear
  public/avatar1.svg
  src/app/(page)/js/page.tsx
  src/components/Card/Card4.tsx
  src/components/Card/Card5.tsx
Labels: ✨ Feature, 🎨 Html&css

#36 feat: 체크박스 컴포넌트 구현 + tsconfig의 컬러추가
  src/app/(page)/dw/page.tsx
  src/components/CheckBox/CheckBox.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Html&css

#37 [FEAT] Textarea (value 및 onChange 함수를 사용하여 입력 값을 제어 구현)
  src/app/(page)/yr/page.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Textarea/Textarea.tsx
  src/components/Textarea/TextareaValue.tsx
Labels: ✨ Feature, 🎨 Html&css

#40 feat: DropDownBasic 컴포넌트 완료
  src/app/(page)/js/page.tsx
  src/components/Card/CardBasic.tsx
  src/components/Card/CardImage.tsx
  src/components/Card/CardInteractive.tsx
  src/components/Card/CardPricing.tsx
  src/components/Card/CardReview.tsx
  src/components/DropDown/DropDownBasic.tsx
  src/components/DropDown/DropDownMutilSelect.tsx
  src/components/RadioButton/RadioButtonBasic.tsx
  src/components/RadioButton/RadioButtonDescription.tsx
  src/components/RadioButton/RadioButtonInline.tsx
Labels: ✨ Feature, 🎨 Html&css

#43 feat: 체크박스 컴포넌트의 체크박스 스타일 추가
  src/app/(page)/dw/page.tsx
  src/components/CheckBox/CheckBox.tsx
Labels: ✨ Feature, 🎨 Html&css

#45 Feature spinner2
  src/app/(page)/sk/page.tsx
  src/components/Spinner/ FullScreenSpinner.tsx
  src/components/Spinner/BarsSpinner.tsx
  src/components/Spinner/BasicSpinner.tsx
  src/components/Spinner/SquareSpinner.tsx
  src/types/type.ts
Labels: ✨ Feature, 🎨 Html&css

#54 feat: Drawer 컴포넌트 구현
  src/app/(page)/dw/page.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/DrawerType.ts
Labels: ✨ Feature, 🎨 Html&css

#55 [feat] basic Select 개발
  public/selectdown.svg
  public/selectup.svg
  src/app/(page)/yr/page.tsx
  src/components/Select/Select.tsx
Labels: ✨ Feature, 🎨 Html&css

#57 Feature Basic modal
  src/app/(page)/sk/page.tsx
  src/components/Modal/BasicModal.tsx
Labels: ✨ Feature, 🎨 Html&css

#60 [FEAT] SelectList 가로형 구현
  src/app/(page)/yr/page.tsx
  src/components/Select/SelectList.tsx
Labels: ✨ Feature, 🎨 Html&css

#62 feat: DropDownGrouped 그룹화된 드롭다운 구현완료
  src/app/(page)/js/page.tsx
  src/components/DropDown/DropDownGrouped.tsx
  src/components/DropDown/DropDownMutilSelect.tsx
Labels: ✨ Feature, 🎨 Html&css

#67 feat: SwtichBasic 기본 스위치 구현완료
  src/app/(page)/js/page.tsx
  src/components/Swtich/SwitchBasic.tsx
Labels: ✨ Feature, 🎨 Html&css

#73 feat: 기본 Toast 컴포넌트 구현
  src/app/(page)/dw/page.tsx
  src/components/Toast/Toast.tsx
  src/types/type.ts
Labels: ✨ Feature, 🎨 Html&css

#79 feat: 스크롤 오버레이 모달 구현
  src/app/(page)/sk/page.tsx
  src/components/Modal/BasicModal.tsx
  src/components/Modal/OverlayModal.tsx
Labels: ✨ Feature, 🎨 Html&css

#81 feat: Form modal
  src/app/(page)/sk/page.tsx
  src/components/Input/Input.tsx
  src/components/Modal/BasicModal.tsx
  src/components/Modal/FormModal.tsx
  src/components/Modal/OverlayModal.tsx
Labels: ✨ Feature, 🎨 Html&css

#84 [Feat] Skeleton basic 기능 구현
  src/app/(page)/yr/page.tsx
  src/components/Select/Select.tsx
  src/components/Select/SelectList.tsx
  src/components/Select/SelectValueAdd.tsx
  src/components/Skeleton/Skeleton.tsx
Labels: ✨ Feature, 🎨 Html&css

#87 feat: 커스터마이징 가능한 Toast 구현
  src/app/(page)/dw/page.tsx
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastColor.ts
  src/components/Toast/ToastPosition.ts
  src/components/Toast/ToastType.ts
Labels: ✨ Feature, 🎨 Html&css

#92 feat: 인풋 클릭시 옵션라벨 생성되는 autocomplete
  public/search.svg
  src/app/(page)/sk/sk2/page.tsx
  src/components/Autocomplete/LabelAutocomplete.tsx
Labels: ✨ Feature, 🎨 Html&css

#82 feat: Infinite Scroll Basic Clear
  public/content/news1.txt
  src/app/(page)/js/page.tsx
  src/components/InfiniteScroll/InfiniteScrollBasic.tsx
Labels: ✨ Feature, 🎨 Html&css

#98 feat: ColorPicker 구현
  src/app/(page)/dw2/page.tsx
  src/components/ColorPicker/ColorPicker.tsx
  src/components/ColorPicker/ColorPickerType.ts
  src/components/ColorPicker/ColorPickerUI.tsx
Labels: ✨ Feature, 🎨 Html&css

#99 feat: 그룹화된 autocomplete
  src/app/(page)/sk/sk2/page.tsx
  src/components/Autocomplete/GroupedAutocomplete.tsx
  src/components/DropDown/DropDownBasic.tsx
  src/components/DropDown/DropDownGrouped.tsx
  src/components/DropDown/DropDownMutilSelect.tsx
Labels: ✨ Feature, 🎨 Html&css

#103 feat : Calender 구현
  src/app/(page)/yr/page.tsx
  src/components/Calendar/Calendar.tsx
Labels: ✨ Feature, 🎨 Html&css

#107 feat: ColorPicker 컴포넌트의 GradientPicker와 TwoPicker 구현
  .gitignore
  src/app/(page)/dw2/page.tsx
  src/components/ColorPicker/ColorPicker.tsx
  src/components/ColorPicker/ColorPickerUI.tsx
  src/components/ColorPicker/GradientPicker.tsx
  src/components/ColorPicker/TwoPicker.tsx
Labels: ✨ Feature, 🎨 Html&css

#108 feat: pagination 구현
  src/app/(page)/sk/sk3/page.tsx
  src/components/Pagination/Pagination.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Html&css

#109 feat: ProgressBarBasic 구현완료
  src/app/(page)/js/page.tsx
  src/components/ProgressBar/ProgressBarBasic.tsx
Labels: ✨ Feature, 🎨 Html&css

#113 feat: 4개 컴포넌트에 대해 ClasName을 통해 커스터마이징이 가능하도록 구현
  src/app/(page)/dw/page.tsx
  src/components/Button/Button.tsx
  src/components/CheckBox/CheckBox.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/DrawerType.ts
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastType.ts
Labels: ✨ Feature, 🎨 Html&css

#114 [feat] Calendar 지정된 날짜 범위 선택하기
  src/app/(page)/yr/page.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarRange.tsx
Labels: ✨ Feature, 🎨 Html&css

#117 feat: ProgressBarSlider 구현완료
  src/app/(page)/js/page.tsx
  src/components/ProgressBar/ProgressBarSlider.tsx
Labels: ✨ Feature, 🎨 Html&css

#125 feat: InfiniteScroll Korean JSON
  src/app/(page)/js/page.tsx
  src/components/ProgressBar/ProgressBarSlider.tsx
Labels: ✨ Feature, 🎨 Html&css

#121 feat: Icon SVG를 Icon Font로 변환하여 프로젝트에 적용
  public/fonts/componique.eot
  public/fonts/componique.svg
  public/fonts/componique.ttf
  public/fonts/componique.woff
  src/app/globals.css
  src/components/Icon/Icon.tsx
Labels: ✨ Feature, 🎨 Html&css

#124 [Feat] basic Carousel 구현
  public/images/next.svg
  public/images/prev.svg
  src/app/(page)/yr/page.tsx
  src/components/Carousel/Carousel.tsx
  src/components/CheckBox/CheckBox.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/DrawerType.ts
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastType.ts
Labels: ✨ Feature, 🎨 Html&css

#134 feat: Drawer 컴포넌트의 아이콘 메뉴 추가
  src/app/(page)/dw/page.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/DrawerType.ts
Labels: ✨ Feature, 🎨 Html&css

#136 [Feat] : Carousel dots 기능 구현
  src/app/(page)/yr/page.tsx
  src/components/Carousel/CarouselDots.tsx
Labels: ✨ Feature, 🎨 Html&css

#141 Feature numinput
  src/app/(page)/sk/sk3/page.tsx
  src/app/(page)/sk/sk4/page.tsx
  src/components/Input/CurrencyInput.tsx
  src/components/Input/DecimalInput.tsx
  src/components/Input/Input.tsx
  src/components/Input/NumInput.tsx
  src/components/Input/PinInput.tsx
  src/components/Pagination/Pagination.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#144 chore: mdx setting
  mdx-components.tsx
  next.config.mjs
  package.json
  src/app/(docs)/button/page.mdx
  src/app/(docs)/input/page.mdx
  src/app/(docs)/layout.tsx
  src/app/markdown.css
  tsconfig.json
Labels: ✨ Feature, 🎨 Html&css

#147 feat: Doc input 구성
  declarations.d.ts
  package.json
  src/app/(docs)/input/page.tsx
  src/app/(docs)/layout.tsx
  src/app/(page)/sk/page.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: 📃 Docs, 🎨 Html&css

#152 feat: icon의 check와 docs 추가
  public/fonts/componique.eot
  public/fonts/componique.svg
  public/fonts/componique.ttf
  public/fonts/componique.woff
  src/app/(page)/dw/page.tsx
  src/app/globals.css
  src/components/Icon/Icon.tsx
Labels: ✨ Feature, 🎨 Html&css

#155 feat: RadioButton decs Page Clear
  src/app/(docs)/radiobutton/page.tsx
Labels: 📃 Docs, 🎨 Html&css

#160 [feat] Navbar Docs
  src/app/(docs)/navbar/page.tsx
  src/app/(page)/yr/page.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/NavbarSearch.tsx
Labels: 📃 Docs, 🎨 Html&css

#167 [Doc] input doc 수정
  src/app/(docs)/input/page.tsx
  src/components/CodeBox.tsx
Labels: 📃 Docs, 🔨 Refactor

#170 chore: code box 수정
  src/components/CodeBox.tsx
Labels: 📃 Docs, 🎨 Html&css

#174 fix: 기존 작성한 Docs를 CodeBox로 수정
  src/app/(docs)/button/page.tsx
  src/app/(docs)/checkbox/page.tsx
Labels: 📃 Docs

#176 feat: Switch Docs Page Clear
  src/app/(docs)/card/page.tsx
  src/app/(docs)/dropdown/page.tsx
  src/app/(docs)/radiobutton/page.tsx
  src/app/(docs)/switch/page.tsx
  src/components/Swtich/SwitchLabeled.tsx
  src/components/Swtich/SwitchRound.tsx
Labels: 📃 Docs, 🎨 Html&css

#184 [Feat] : Select Docs 구현
  public/selectDownGray.svg
  public/selectDownGreen.svg
  public/selectDownRed.svg
  public/selectUpGray.svg
  public/selectUpGreen.svg
  public/selectUpRed.svg
  src/app/(docs)/select/page.tsx
  src/app/(page)/yr/page.tsx
  src/app/globals.css
  src/components/Select/Select.tsx
  src/components/Select/SelectList.tsx
  src/components/Select/SelectValueAdd.tsx
Labels: 📃 Docs, ✨ Feature, 🎨 Html&css

#193 [Doc] spinner 및 input doc 세부 수정
  src/app/(docs)/input/page.tsx
  src/app/(docs)/spinner/page.tsx
  src/components/Input/Input.tsx
  src/components/Spinner/BasicSpinner.tsx
  src/components/Spinner/SquareSpinner.tsx
Labels: 📃 Docs, 🔨 Refactor

#217 [IMPR] : docs codebox수정 및 css수정
  src/app/(docs)/calendar/page.tsx
  src/app/(docs)/carousel/page.tsx
  src/app/(docs)/navbar/page.tsx
  src/app/(docs)/select/page.tsx
  src/app/(docs)/textarea/page.tsx
Labels: 📃 Docs, 🔨 Refactor

#219 docs: toast 통합과 구분선 추가
  src/app/(docs)/colorpicker/page.tsx
  src/app/(docs)/toast/page.tsx
  src/app/(docs)/toastgroup/page.tsx
Labels: 📃 Docs

#223 doc 수정 (#213)
  src/app/(docs)/autocomplete/page.tsx
  src/app/(docs)/input/page.tsx
  src/app/(docs)/modal/page.tsx
  src/app/(docs)/spinner/page.tsx
Labels: 📃 Docs

#228 feat: 사이드바와 상단바 레이아웃 구현
  src/app/globals.css
  src/app/layout.tsx
  src/components/Layout/Logo.tsx
  src/components/Layout/SideBar.tsx
Labels: ✨ Feature, 🎨 Html&css

#229 [FEAT] 메인페이지 autocomplete,최근검색어 저장
  public/Componique.svg
  src/app/page.tsx
  src/components/Autocomplete.tsx
Labels: ✨ Feature, 🎨 Html&css

#230 feat: Main Content Page Clear
  public/AutoComplete.svg
  public/Avatar.svg
  public/Button.svg
  public/Calender.svg
  public/Card.svg
  public/Carousel.svg
  public/CheckBox.svg
  public/ColorPicker.svg
  public/Drawer.svg
  public/DropDown.svg
  public/Icon.svg
  public/InfiniteScroll.svg
  public/Input.svg
  public/Modal.svg
  public/Navbar.svg
  public/Pagination.svg
  public/RadioButton.svg
  public/Select.svg
  public/Skeleton.svg
  public/Spinner.svg
  public/Switch.svg
  public/Textarea.svg
  public/Toast.svg
  src/app/page.tsx
  src/components/Content/page.tsx
  src/components/DropDown/DropDownBasic.tsx
  src/components/DropDown/DropDownGrouped.tsx
  src/components/DropDown/DropDownMutilSelect.tsx
Labels: ✨ Feature, 🎨 Html&css

#239 feat: footer 1 clear
  package.json
  src/app/layout.tsx
  src/components/Footer/Footer.tsx
Labels: ✨ Feature, 🎨 Html&css

#240 feat: 반응형 레이아웃과 유지보수 및 Drawer 관련
  src/app/(docs)/drawer/page.tsx
  src/app/(docs)/layout.tsx
  src/app/(page)/dw/page.tsx
  src/app/layout.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/DrawerType.ts
  src/components/Layout/HamburgerMenu.tsx
  src/components/Layout/Header.tsx
  tailwind.config.ts
Labels: 📃 Docs, ✨ Feature, 🎨 Html&css, 🔨 Refactor

#241 Feature #231
  src/app/(docs)/autocomplete/page.tsx
  src/app/(docs)/input/page.tsx
  src/app/(docs)/pagination/page.tsx
  src/components/Autocomplete/Autocomplete.tsx
  src/components/Autocomplete/ButtonAutocomplete.tsx
  src/components/Autocomplete/GroupedAutocomplete.tsx
  src/components/Input/CurrencyInput.tsx
  src/components/Input/DecimalInput.tsx
  src/components/Input/NumInput.tsx
  src/components/Input/SearchInput.tsx
  src/components/Input/SearchInput2.tsx
  src/components/Input/SearchInput3.tsx
  src/components/Pagination/Pagination.tsx
Labels: 🐞 BugFix
