Repository Poten14/Componique, pull requests merged in 2024-09, with the labels that each got.

#252 fix: 모달 버그 수정 및 cicd테스트 (#251)
  src/app/(docs)/modal/page.tsx
  src/app/(page)/sk/page.tsx
Labels: 🐞 BugFix, 📃 Docs, ✨ Chore

#245 feat : 코드박스,컴포넌트 간격 넓히기 구현(#242)
  src/app/(docs)/calendar/page.tsx
  src/app/(docs)/carousel/page.tsx
  src/app/(docs)/navbar/page.tsx
  src/app/(docs)/select/page.tsx
  src/app/(docs)/skeleton/page.tsx
  src/app/(docs)/textarea/page.tsx
  src/app/globals.css
  src/components/Quickmenu/Quickmenu.tsx
Labels: ✨ Feature, 🎨 Html&css

#247 [Fix] docs수정 및 중복되는 최근검색어 수정
  src/app/(docs)/autocomplete/page.tsx
  src/app/(docs)/input/page.tsx
  src/app/(docs)/modal/page.tsx
  src/app/(docs)/pagination/page.tsx
  src/app/(docs)/spinner/page.tsx
  src/app/page.tsx
  src/components/CodeBox.tsx
  tailwind.config.ts
Labels: 🔨 Refactor

#249 feat: Footer 컴포넌트 구현
  public/FooterLogo.svg
  src/components/Footer/Footer.tsx
Labels: ✨ Feature, 🎨 Html&css

#250 docs: 컴포넌트 별 SPAN 작업 + icon(github, blog 추가)
  public/fonts/componique.eot
  public/fonts/componique.svg
  public/fonts/componique.ttf
  public/fonts/componique.woff
  src/app/(docs)/button/page.tsx
  src/app/(docs)/checkbox/page.tsx
  src/app/(docs)/colorpicker/page.tsx
  src/app/(docs)/drawer/page.tsx
  src/app/(docs)/icon/page.tsx
  src/app/(docs)/toast/page.tsx
  src/app/globals.css
  src/components/Icon/Icon.tsx
Labels: 📃 Docs, ✨ Feature, 🎨 Html&css

#254 style: 코드박스 css수정
  src/components/CodeBox.tsx
Labels: 🎨 Html&css

#257 feat: dark mode switch 구현
  public/Moon.svg
  public/Sun.svg
  src/app/(page)/js/page.tsx
  src/components/Footer/Footer.tsx
  src/components/Swtich/SwitchDark.tsx
Labels: ✨ Feature, 🎨 Html&css

#260 [Doc] input 목차 수정
  src/app/(docs)/input/page.tsx
Labels: 📃 Docs

#263 chore: 메인페이지에만 배경이 적용되도록 구현
  src/app/globals.css
  src/app/page.tsx
Labels: 📃 Docs, 🎨 Html&css, 🔨 Refactor

#264 [Feat] : QuickMenu 코드 수정 및 개발
  src/app/(docs)/layout.tsx
  src/app/(docs)/skeleton/page.tsx
  src/app/globals.css
  src/components/Quickmenu/Quickmenu.tsx
Labels: ✨ Feature, 🎨 Html&css

#271 docs: ImageUpload 컴포넌트의 Docs 추가
  src/app/(docs)/imageupload/page.tsx
Labels: 📃 Docs, 🎨 Html&css

#279 feat: Docs Page DarkMode Clear
  src/app/(docs)/card/page.tsx
  src/app/(docs)/dropdown/page.tsx
  src/app/(docs)/infinitescroll/page.tsx
  src/app/(docs)/progressbar/page.tsx
  src/app/(docs)/radiobutton/page.tsx
  src/app/(docs)/switch/page.tsx
Labels: 📃 Docs, ✨ Feature, 🎨 Html&css

#283 feat: 다크모드 구현
  src/components/CheckBox/CheckBox.tsx
  src/components/ColorPicker/ColorPickerUI.tsx
  src/components/ColorPicker/GradientPicker.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/DrawerType.ts
  src/components/Layout/Header.tsx
  src/components/Toast/ToastColor.ts
Labels: 📃 Docs, ✨ Feature, 🎨 Html&css

#289 [feat] darkmode 컴포넌트 css 수정
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/NavbarSearch.tsx
  src/components/Select/Select.tsx
  src/components/Select/SelectList.tsx
  src/components/Select/SelectValueAdd.tsx
Labels: 📃 Docs, 🎨 Html&css, 🔨 Refactor

#293 feat: 사용자 페이지를 위한 레이아웃 구현
  src/app/(docs)/layout.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/userpage/(template)/layout.tsx
  src/app/userpage/(template)/webtoon/page.tsx
  src/app/userpage/layout.tsx
  src/app/userpage/page.tsx
  src/components/Layout/UserPage.tsx
  src/components/Layout/UserPagePrevButton.tsx
Labels: ✨ Feature, 🎨 Html&css

#296 add: 사이드바와 햄버거 메뉴에 Progress bar 추가
  src/components/Layout/Header.tsx
  src/components/Layout/SideBar.tsx
Labels: ✨ Feature, 🎨 Html&css

#300 [Fix] 각종 doc에서 발생하는 에러 수정
  src/app/(docs)/input/page.tsx
  src/app/(docs)/modal/page.tsx
  src/components/Autocomplete/Autocomplete.tsx
  src/components/Autocomplete/ButtonAutocomplete.tsx
  src/components/Autocomplete/GroupedAutocomplete.tsx
  src/components/Input/Input.tsx
  src/components/Input/PinInput.tsx
  src/components/Input/SearchInput.tsx
Labels: 🐞 BugFix, 📃 Docs

#302 impr: QA 1차 수정
  src/app/(docs)/avatar/page.tsx
  src/app/(docs)/dropdown/page.tsx
  src/app/(docs)/radiobutton/page.tsx
  src/app/(docs)/switch/page.tsx
  src/components/Card/CardBasic.tsx
  src/components/Card/CardImage.tsx
  src/components/Card/CardInteractive.tsx
  src/components/Card/CardPricing.tsx
  src/components/Card/CardReview.tsx
  src/components/Footer/Footer.tsx
Labels: 📃 Docs, 🎨 Html&css

#306 [fix] : NavbarSearch 코드 수정
  src/app/(docs)/navbar/page.tsx
  src/components/Quickmenu/Quickmenu.tsx
Labels: 📃 Docs, 🎨 Html&css

#312 impr: TextAreaDark 수정
  src/components/Content/page.tsx
Labels: 📃 Docs, 🎨 Html&css, 🔨 Refactor

#314 feat: 아이콘 댓글 추가
  public/fonts/componique.eot
  public/fonts/componique.svg
  public/fonts/componique.ttf
  public/fonts/componique.woff
  src/app/(docs)/icon/page.tsx
  src/app/globals.css
  src/components/Icon/Icon.tsx
Labels: ✨ Feature, 🎨 Html&css

#319 [feat] : select 수정
  src/app/(docs)/select/page.tsx
  src/app/(page)/yr/page.tsx
  src/components/Select/Select.tsx
Labels: ✨ Feature, 🎨 Html&css

#321 impr: DropdownReview, Main Toast Image Clear
  public/Toast.svg
  src/app/(docs)/dropdown/page.tsx
  src/app/(page)/js/page.tsx
  src/components/DropDown/DropDownBasic.tsx
  src/components/DropDown/DropDownGrouped.tsx
  src/components/DropDown/DropDownMutilSelect.tsx
Labels: 📃 Docs, 🎨 Html&css, 🔨 Refactor

#322 feat: 유저페이지 리모컨
  src/app/userpage/(template)/layout.tsx
  src/app/userpage/(template)/login/RemoteControl.tsx
  src/app/userpage/(template)/login/components/LoginForm.tsx
  src/app/userpage/(template)/login/page.tsx
  src/app/userpage/Remote/Remote.tsx
  src/app/userpage/Remote/useRemote.tsx
  src/components/Button/Button.tsx
Labels: ✨ Feature

#325 feat: userpage colorpicker
  src/app/userpage/(template)/colorpicker/page.tsx
  src/components/ColorPicker/ColorPicker.tsx
  src/components/ColorPicker/ColorPickerUI.tsx
  src/components/ColorPicker/GradientPicker.tsx
  src/components/ColorPicker/TwoPicker.tsx
Labels: ✨ Feature, 🎨 Html&css

#326 feat : select prop 수정, RemoteControl 테스트
  src/app/(docs)/select/page.tsx
  src/app/(page)/yr/page.tsx
  src/app/userpage/(template)/login/RemoteControl.tsx
  src/components/Select/Select.tsx
  src/components/Select/SelectList.tsx
  src/components/Select/SelectValueAdd.tsx
Labels: ✨ Feature, 🎨 Html&css

#332 feat: 사용자 페이지 레이아웃 수정
  src/app/userpage/(template)/colorpicker/page.tsx
  src/app/userpage/(template)/layout.tsx
  src/app/userpage/(template)/login/components/LoginForm.tsx
  src/app/userpage/(template)/login/page.tsx
  src/app/userpage/Remote/Remote.tsx
Labels: ✨ Feature, 🎨 Html&css

#338 feat: ImageUpload의 Icon 추가
  src/app/(page)/dw/dw4/page.tsx
  src/components/ImageUpload/Imageupload.tsx
Labels: ✨ Feature, 🎨 Html&css

#353 chore: 프로필 사용자 페이지 유지보수
  src/app/userpage/(template)/profile/components/Profile.tsx
  src/app/userpage/(template)/profile/page.tsx
  src/app/userpage/Remote/RemoteProfile.tsx
Labels: 🔨 Refactor

#357 feat: customer service 구현
  src/app/store/useServiceStore.ts
  src/app/userpage/(template)/customerservice/components/customerserviceform.tsx
  src/app/userpage/(template)/customerservice/page.tsx
  src/app/userpage/Remote/CustomerServiceRemote.tsx
Labels: ✨ Feature, 🎨 Html&css

#364 [FEAT] 쇼핑페이지 템플릿 구현
  src/app/store/useShoppingStore.ts
  src/app/userpage/(template)/login/page.tsx
  src/app/userpage/(template)/shopping/components/ShoppingForm.tsx
  src/app/userpage/(template)/shopping/page.tsx
  src/app/userpage/(template)/webtoon/page.tsx
  src/app/userpage/Remote/RemoteLogin.tsx
  src/app/userpage/Remote/RemoteShopping.tsx
  src/components/Navbar/Navbar.tsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css

#365 [FEAT] todolist 템플릿 구현
  src/app/store/useSnsStore.ts
  src/app/store/useTodoListStore.ts
  src/app/userpage/(template)/sns/Remote.tsx
  src/app/userpage/(template)/sns/components/SnsForm.tsx
  src/app/userpage/(template)/sns/page.tsx
  src/app/userpage/(template)/todolist/components/TodolistForm.tsx
  src/app/userpage/(template)/todolist/page.tsx
  src/app/userpage/Remote/RemoteTodoList.tsx
  src/components/Carousel/CarouselDots.tsx
  src/components/Textarea/Textarea.tsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css

#377 chore: Profile 사용자 페이지 Remote UI 수정
  src/app/userpage/(template)/profile/page.tsx
  src/app/userpage/Remote/RemoteProfile.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#381 [Feat] : Sns 페이지 구현
  src/app/store/useSnsStore.ts
  src/app/userpage/(template)/sns/components/Sns.tsx
  src/app/userpage/(template)/sns/page.tsx
  src/app/userpage/Remote/RemoteSns.tsx
  src/components/Carousel/Carousel.tsx
  src/components/Carousel/CarouselAutoplay.tsx
  src/components/Carousel/CarouselDots.tsx
Labels: ✨ Feature, 🎨 Html&css

#384 impr: Remote Name Change
  src/app/store/useCalenderStore.ts
  src/app/userpage/(template)/booking/components/calendarform.tsx
  src/app/userpage/(template)/booking/page.tsx
  src/app/userpage/(template)/customerservice/page.tsx
  src/app/userpage/Remote/RemoteCalendar.tsx
  src/app/userpage/Remote/RemoteCustomerService.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#394 [FEAT] 로그인 폼 추가 및 리모콘 스타일 조정
  src/app/store/useLoginStore.ts
  src/app/store/useShoppingStore 2.ts
  src/app/userpage/(template)/login/components/LoginForm.tsx
  src/app/userpage/(template)/login/page.tsx
  src/app/userpage/(template)/shopping/components/ShoppingForm.tsx
  src/app/userpage/Remote/RemoteLogin.tsx
  src/app/userpage/Remote/RemoteShopping.tsx
Labels: ✨ Feature, 🎨 Html&css

#398 feat: 하트 아이콘 추가
  public/fonts/componique.eot
  public/fonts/componique.svg
  public/fonts/componique.ttf
  public/fonts/componique.woff
  src/app/(docs)/icon/page.tsx
  src/app/globals.css
  src/components/Icon/Icon.tsx
Labels: ✨ Feature, 🎨 Html&css

#400 feat: 파비콘 변경
  src/app/favicon.ico
Labels: ✨ Feature, 🎨 Html&css

#403 [Feat] : Sns 사용자페이지 css 수정
  src/app/userpage/(template)/sns/components/Sns.tsx
  src/app/userpage/(template)/sns/page.tsx
  src/app/userpage/(template)/todolist/components/TodolistForm.tsx
Labels: ✨ Feature, 🎨 Html&css

#405 chore: remote 수정 (profile, survey, login, shopping)
  src/app/userpage/(template)/shopping/page.tsx
  src/app/userpage/(template)/todolist/page.tsx
  src/app/userpage/Remote/RemoteLogin.tsx
  src/app/userpage/Remote/RemoteProfile.tsx
  src/app/userpage/Remote/RemoteShopping.tsx
  src/app/userpage/Remote/RemoteSns.tsx
  src/app/userpage/Remote/RemoteSurvey.tsx
  src/app/userpage/Remote/RemoteTodoList.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Html&css

#416 save
  public/ColorPickerDark.svg
Labels: 🎨 Html&css, 🔨 Refactor

#418 chore: 프로필 사용자 페이지 수정
  src/app/store/useProfileStore.ts
  src/app/userpage/(template)/profile/components/Profile.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#421 [chore] : sns, todolist darkmode 구현 및 수정
  src/app/userpage/(template)/sns/components/Sns.tsx
  src/app/userpage/(template)/todolist/components/TodolistForm.tsx
Labels: ✨ Feature, 🎨 Html&css

#426 feat: 404page
  public/404Button-Docs-Dark.svg
  public/404Button-Docs.svg
  public/404Button-User-Dark.svg
  public/404Button-User.svg
  public/404Image.svg
  public/404ImageDark.svg
  src/app/404/page.tsx
  src/app/store/useCalenderStore.ts
  src/app/userpage/(template)/booking/components/calendarform.tsx
  src/app/userpage/(template)/booking/page.tsx
  src/app/userpage/Remote/RemoteCalendar.tsx
Labels: ✨ Feature, 🎨 Html&css

#431 feat: 사용자 페이지 리스트 구현
  public/userColorpicker.svg
  public/userColorpickerDark.svg
  public/userCustomerservice.svg
  public/userCustomerserviceDark.svg
  public/userLogin.svg
  public/userLoginDark.svg
  public/userSurvey.svg
  public/userSurveyDark.svg
  public/userTodolist.svg
  public/userTodolistDark.svg
  src/app/userpage/(template)/layout.tsx
  src/app/userpage/layout.tsx
  src/app/userpage/page.tsx
  src/components/Layout/Header.tsx
  src/components/Layout/UserPage.tsx
  src/components/Layout/UserPageLeftSidebar.tsx
  src/components/Layout/UserPageLogoText.tsx
  src/components/Layout/UserPagePrevButton.tsx
Labels: ✨ Feature, 🎨 Html&css

#438 feat: icon 추가
  public/fonts/componique.eot
  public/fonts/componique.svg
  public/fonts/componique.ttf
  public/fonts/componique.woff
  src/app/(docs)/icon/page.tsx
  src/app/globals.css
  src/components/Icon/Icon.tsx
Labels: ✨ Feature, 🎨 Html&css

#439 fix: twitter 아이콘 고침
  public/fonts/componique.eot
  public/fonts/componique.svg
  public/fonts/componique.ttf
  public/fonts/componique.woff
Labels: ✨ Feature, 🎨 Html&css

#441 feat: drawer와 sidebar에 메뉴 추가
  src/components/Layout/Header.tsx
  src/components/Layout/SideBar.tsx
Labels: ✨ Feature, 🎨 Html&css

#443 chore: breadcrumb 오타 수정
  src/components/Layout/Header.tsx
  src/components/Layout/SideBar.tsx
Labels: 🎨 Html&css

#445 chore: 사용자 페이지 개선
  src/app/userpage/(template)/customerservice/page.tsx
  src/app/userpage/(template)/login/page.tsx
  src/app/userpage/(template)/profile/components/Profile.tsx
  src/app/userpage/(template)/profile/page.tsx
  src/app/userpage/(template)/shopping/page.tsx
  src/app/userpage/(template)/sns/components/Sns.tsx
  src/app/userpage/(template)/sns/page.tsx
  src/app/userpage/(template)/survey/components/Survey.tsx
  src/app/userpage/(template)/survey/page.tsx
  src/app/userpage/(template)/todolist/components/TodolistForm.tsx
  src/app/userpage/(template)/todolist/page.tsx
  src/app/userpage/layout.tsx
  src/components/Carousel/CarouselDots.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Layout/Header.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#448 Impr: ChangeAvatar
  public/avatar1.svg
Labels: 🎨 Html&css, 🔨 Refactor

#450 [IMPR] : BreadCrumb component 수정
  src/components/BreadCrumb/BreadCrumb.tsx
  src/components/BreadCrumb/BreadCrumbDropdown.tsx
  src/components/BreadCrumb/BreadCrumbSlash.tsx
Labels: ✨ Feature, 🎨 Html&css

#455 [FEAT] 코드 복사 기능 및 여러가지 스타일 수정
  src/app/(docs)/autocomplete/page.tsx
  src/app/(docs)/avatar/page.tsx
  src/app/(docs)/button/page.tsx
  src/app/(docs)/calendar/page.tsx
  src/app/(docs)/card/page.tsx
  src/app/(docs)/carousel/page.tsx
  src/app/(docs)/checkbox/page.tsx
  src/app/(docs)/colorpicker/page.tsx
  src/app/(docs)/drawer/page.tsx
  src/app/(docs)/dropdown/page.tsx
  src/app/(docs)/icon/page.tsx
  src/app/(docs)/imageupload/page.tsx
  src/app/(docs)/infinitescroll/page.tsx
  src/app/(docs)/input/page.tsx
  src/app/(docs)/modal/page.tsx
  src/app/(docs)/navbar/page.tsx
  src/app/(docs)/pagination/page.tsx
  src/app/(docs)/progressbar/page.tsx
  src/app/(docs)/radiobutton/page.tsx
  src/app/(docs)/select/page.tsx
  src/app/(docs)/skeleton/page.tsx
  src/app/(docs)/spinner/page.tsx
  src/app/(docs)/switch/page.tsx
  src/app/(docs)/textarea/page.tsx
  src/app/(docs)/toast/page.tsx
  src/app/(docs)/tooltip/page.tsx
  src/app/layout.tsx
  src/app/store/useLoginStore.ts
  src/app/store/useProfileStore.ts
  src/app/store/useServiceStore.ts
  src/app/store/useShoppingStore 2.ts
  src/app/store/useShoppingStore.ts
  src/app/store/useSurveyStore.ts
  src/app/store/useTodoListStore.ts
  src/app/userpage/(template)/colorpicker/page.tsx
  src/app/userpage/(template)/customerservice/components/customerserviceform.tsx
  src/app/userpage/(template)/login/components/LoginForm.tsx
  src/app/userpage/(template)/shopping/components/ShoppingForm.tsx
  src/app/userpage/Remote/RemoteCustomerService.tsx
  src/app/userpage/Remote/RemoteLogin.tsx
  src/app/userpage/Remote/RemoteProfile.tsx
  src/app/userpage/Remote/RemoteShopping.tsx
  src/app/userpage/Remote/RemoteSns.tsx
  src/app/userpage/Remote/RemoteSurvey.tsx
  src/app/userpage/Remote/RemoteTodoList.tsx
  src/components/Modal/BasicModal.tsx
  src/components/Select/SelectValueAdd.tsx
Labels: ✨ Feature, 🎨 Html&css

#451 feat: Badge Component 구현 완료
  src/app/(docs)/badge/page.tsx
  src/app/(page)/js2/page.tsx
  src/components/Avatar/AvatarBasic.tsx
  src/components/Badge/Badge.tsx
  src/components/Badge/BadgeBasic.tsx
  src/components/Badge/BadgeCounter.tsx
  src/components/Badge/BadgeDot.tsx
  src/components/Badge/BadgeIcon.tsx
Labels: ✨ Feature, 🎨 Html&css

#453 feat: Badge Docs Page Clear
  src/app/(docs)/badge/page.tsx
  src/app/(docs)/card/page.tsx
Labels: 📃 Docs, ✨ Feature, 🎨 Html&css

#457 feat: Rage컴포넌트 구현
  package.json
  src/app/(docs)/card/page.tsx
  src/app/(page)/js2/page.tsx
  src/components/Map/MapBasic.tsx
  src/components/Rating/RatingFeel.tsx
  src/components/Rating/RatingNumSlider.tsx
  src/components/Rating/RatingStar.tsx
Labels: ✨ Feature, 🎨 Html&css

#465 Feature form validation
  package.json
  public/Validation.svg
  public/ValidationDark.svg
  src/app/(docs)/validation/page.tsx
  src/app/(page)/js2/page.tsx
  src/components/Content/page.tsx
  src/components/Layout/Header.tsx
  src/components/Validation/ValidationEmail.tsx
  src/components/Validation/ValidationID.tsx
  src/components/Validation/ValidationPW.tsx
  src/components/Validation/ValidationPWConfirm.tsx
  src/components/Validation/ValidationPhone.tsx
Labels: ✨ Feature, 🎨 Html&css

#469 feat: BasicDataTable 구현
  src/app/(page)/js2/page.tsx
  src/components/DataTable/DataTableBasic.tsx
Labels: ✨ Feature, 🎨 Html&css

#471 feat: Basic Map clear
  package.json
  src/app/(page)/js2/page.tsx
  src/components/Map/DynamicMap.tsx
  src/components/Map/MapBasic.tsx
Labels: ✨ Feature, 🎨 Html&css

#473 feat: Map Position 구현
  src/app/(page)/js2/page.tsx
  src/components/Map/DynamicMapPosition.tsx
  src/components/Map/MapBasic.tsx
  src/components/Map/MapLive.tsx
  src/components/Map/MapPosition.tsx
Labels: ✨ Feature, 🎨 Html&css

#480 feat: Card Page Chagne
  package.json
  src/app/(docs)/card/page.tsx
Labels: 📃 Docs, 🎨 Html&css, 🔨 Refactor

#485 [Feat] : introduction page
  src/app/(docs)/introduction/page.tsx
  src/components/Layout/SideBar.tsx
Labels: ✨ Feature, 🎨 Html&css

#490 feat : skeleton css수정(#26)
  src/components/Skeleton/SkeletonCard.tsx
Labels: 🎨 Html&css

#494 fix: npm 관련 배포 수정
  .gitignore
  package.json
  src/components/Map/DynamicMapPosition.tsx
  src/components/Map/MapPosition.tsx
  src/index.ts
  tsconfig.json
Labels: 🐞 BugFix, ✨ Chore

#495 add: pakege.json 버전 업데이트
  package.json
Labels: ✨ Feature

#496 fix: npm 관련 fix
  tsconfig.json
Labels: ✨ Chore

#497 fix: npm 수정
  package.json
  tsconfig.json
Labels: ✨ Chore

#498 fix: git ignore 수정
  .gitignore
  package.json
Labels: ✨ Chore
